import { calculateBudget, formatCurrency } from '../utils/calculations'
import { clientDisplayName, calculateClientMetrics } from '../utils/clients'

export default function ClientDetails({ client, budgets, onBack, onOpenProposal, onEditClient, onNewProposal }) {
  const metrics = calculateClientMetrics(client, budgets)
  const related = budgets.filter((budget) => budget.clientId === client.id)
  const approvalRate = metrics.proposalCount ? Math.round(metrics.approvedProposalCount / metrics.proposalCount * 100) : 0
  return <main className="page-wrap app-page client-details-page"><header className="topbar"><button className="brand" onClick={onBack}><span className="logo-mark">V</span><span>Vetra</span></button><button className="button" onClick={() => onNewProposal(client)}>Nova proposta <span>＋</span></button></header><button className="back-link" onClick={onBack}>← Voltar para clientes</button><section className="client-detail-hero"><div><span className="card-kicker">PERFIL DO CLIENTE</span><h1>{clientDisplayName(client)}</h1><p>{client.type === 'pessoa_juridica' ? 'Pessoa jurídica' : 'Pessoa física'} · {client.source || 'Origem não informada'}</p></div><button className="button button-secondary" onClick={() => onEditClient(client)}>Editar cliente</button></section><section className="client-detail-layout"><div className="client-detail-main"><section className="glass-panel detail-panel"><h2>Dados principais</h2><div className="details-summary"><Info label="Telefone" value={client.phone} /><Info label="E-mail" value={client.email} /><Info label="CPF / CNPJ" value={client.cpf || client.cnpj} /><Info label="Endereço" value={[client.address, client.city, client.state].filter(Boolean).join(', ')} /></div><h3>Tags</h3><div className="client-tags">{client.tags.length ? client.tags.map((tag) => <span key={tag}>{tag}</span>) : <small>Nenhuma tag cadastrada</small>}</div><h3>Observações</h3><p className="detail-copy">{client.notes || 'Nenhuma observação cadastrada.'}</p></section><section className="glass-panel detail-panel"><div className="panel-heading"><div><span className="eyebrow">RELACIONAMENTO</span><h2>Histórico de propostas</h2></div><button className="text-button" onClick={() => onNewProposal(client)}>＋ Nova proposta</button></div>{related.length ? <div className="client-proposals">{related.map((budget) => <article key={budget.id}><div><span className="proposal-number">{budget.proposalNumber}</span><h3>{budget.projectName || 'Projeto sem nome'}</h3><p>{budget.category} · {budget.status}</p></div><strong>{formatCurrency(calculateBudget(budget).sustainablePrice)}</strong><div><button className="text-button" onClick={() => onOpenProposal(budget)}>Abrir</button></div></article>)}</div> : <p className="detail-copy">Nenhuma proposta vinculada a este cliente.</p>}</section></div><aside className="client-stat-card"><span className="card-kicker">VISÃO DO CLIENTE</span><Stat label="Total de propostas" value={metrics.proposalCount} /><Stat label="Propostas aprovadas" value={metrics.approvedProposalCount} /><Stat label="Taxa de aprovação" value={`${approvalRate}%`} /><Stat label="Receita acumulada" value={formatCurrency(metrics.totalRevenue)} /><Stat label="Último contato" value={formatDate(metrics.lastContactAt)} /></aside></section></main>
}
function Info({ label, value }) { return <div className="details-info"><span>{label}</span><strong>{value || 'Não informado'}</strong></div> }
function Stat({ label, value }) { return <div className="client-stat"><span>{label}</span><strong>{value}</strong></div> }
function formatDate(value) { if (!value) return 'Não informado'; try { return new Intl.DateTimeFormat('pt-BR', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(value)) } catch { return 'Não informado' } }
