import { createPortal } from 'react-dom'
import { useMemo, useState } from 'react'
import { calculateClientMetrics, clientDisplayName, createClient, CLIENT_SOURCES } from '../utils/clients'
import { formatCurrency } from '../utils/calculations'
import { GlassCard } from './ui'

export default function ClientsView({ clients, budgets, onOpen, onSave, onDelete, onNew }) {
  const [search, setSearch] = useState('')
  const [filter, setFilter] = useState('todos')
  const [sort, setSort] = useState('recentes')
  const filtered = useMemo(() => {
    const result = clients.filter((client) => {
      const text = `${clientDisplayName(client)} ${client.email} ${client.phone} ${client.tags.join(' ')}`.toLocaleLowerCase('pt-BR')
      const matchesFilter = filter === 'todos' || (filter === 'favoritos' ? client.favorite : client.status === filter)
      return text.includes(search.toLocaleLowerCase('pt-BR')) && matchesFilter
    }).map((client) => ({ ...client, ...calculateClientMetrics(client, budgets) }))
    return result.sort((a, b) => sort === 'nome' ? clientDisplayName(a).localeCompare(clientDisplayName(b), 'pt-BR') : sort === 'faturamento' ? b.totalRevenue - a.totalRevenue : sort === 'propostas' ? b.proposalCount - a.proposalCount : String(b.updatedAt).localeCompare(String(a.updatedAt)))
  }, [clients, budgets, filter, search, sort])
  return <div className="clients-page"><section className="subpage-heading"><div className="eyebrow">RELACIONAMENTOS</div><h1>Clientes</h1><p>Organize pessoas e empresas por trás de cada proposta.</p></section><div className="client-toolbar"><label className="search"><span>⌕</span><input value={search} onChange={(event) => setSearch(event.target.value)} aria-label="Buscar clientes" placeholder="Buscar cliente, e-mail ou tag" /></label><select aria-label="Filtrar clientes" value={filter} onChange={(event) => setFilter(event.target.value)}><option value="todos">Todos</option><option value="ativo">Ativos</option><option value="inativo">Inativos</option><option value="favoritos">Favoritos</option></select><select aria-label="Ordenar clientes" value={sort} onChange={(event) => setSort(event.target.value)}><option value="recentes">Mais recentes</option><option value="nome">Nome</option><option value="faturamento">Maior valor contratado</option><option value="propostas">Mais propostas</option></select></div>{filtered.length ? <div className="clients-grid">{filtered.map((client) => <ClientCard key={client.id} client={client} onOpen={onOpen} onSave={onSave} onDelete={onDelete} />)}</div> : <div className="empty-state"><div className="empty-icon">✦</div><h3>{search ? 'Nenhum cliente encontrado' : 'Sua base de clientes começa aqui'}</h3><p>Cadastre um cliente para vincular propostas e acompanhar o relacionamento.</p><button className="button" onClick={onNew}>Criar cliente <span>＋</span></button></div>}</div>
}

function ClientCard({ client, onOpen, onSave, onDelete }) { const [editing, setEditing] = useState(false); const metrics = client; const save = (data) => { if (onSave({ ...client, ...data, updatedAt: new Date().toISOString() }) === false) return false; setEditing(false) }; return <GlassCard as="article" className="client-card"><button className={`favorite-button ${client.favorite ? 'is-favorite' : ''}`} onClick={() => onSave({ ...client, favorite: !client.favorite, updatedAt: new Date().toISOString() })} aria-label={client.favorite ? 'Remover cliente dos favoritos' : 'Favoritar cliente'}>{client.favorite ? '★' : '☆'}</button><span className="status-chip">{client.status === 'ativo' ? 'Ativo' : 'Inativo'}</span><h2>{clientDisplayName(client)}</h2><p className="client-type">{client.type === 'pessoa_juridica' ? 'Pessoa jurídica' : 'Pessoa física'}{client.source ? ` · ${client.source}` : ''}</p><div className="client-contact"><span>{client.phone || 'Telefone não informado'}</span><span>{client.email || 'E-mail não informado'}</span></div><div className="client-tags">{client.tags.map((tag) => <span key={tag}>{tag}</span>)}</div><div className="client-metrics"><Info label="Propostas" value={metrics.proposalCount} /><Info label="Contratado" value={formatCurrency(metrics.totalRevenue)} /><Info label="Última atividade / evento" value={formatDate(metrics.lastActivityAt)} /></div><div className="client-actions"><button className="button button-secondary" onClick={() => onOpen(client)}>Abrir</button><button className="text-button" onClick={() => setEditing(true)}>Editar</button><button className="text-button danger-button" onClick={() => onDelete(client.id)}>Excluir</button></div>{editing && <ClientForm initial={client} onSave={save} onClose={() => setEditing(false)} />}</GlassCard> }
function Info({ label, value }) { return <div><span>{label}</span><strong>{value}</strong></div> }
function formatDate(value) { if (!value) return 'Não informado'; try { return new Intl.DateTimeFormat('pt-BR', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(value)) } catch { return 'Não informado' } }
export function ClientForm({ initial, onSave, onClose }) {
  const [data, setData] = useState(() => ({ ...createClient(), ...(initial || {}) }))
  const [error, setError] = useState('')
  const update = (key, value) => setData((current) => ({ ...current, [key]: value }))
  const submit = (event) => { event.preventDefault(); if (!(data.type === 'pessoa_juridica' ? data.companyName : data.name).trim()) return; if (onSave(data) === false) setError('Não foi possível salvar. Seus dados continuam neste formulário.') }
  return createPortal(<div className="document-overlay client-form-overlay"><form className="settings-modal client-form" role="dialog" aria-modal="true" aria-label="Cadastro de cliente" onSubmit={submit}>
    <div className="modal-heading"><div><span className="card-kicker">BASE DE CLIENTES</span><h2>{initial ? 'Editar cliente' : 'Novo cliente'}</h2></div><button type="button" className="modal-close" onClick={onClose} aria-label="Fechar formulário">×</button></div>
    <div className="settings-scroll"><p className="form-help">Comece pelo nome e um contato. Complete os dados comerciais quando precisar.</p><label className="field"><span>Tipo</span><select value={data.type} onChange={(event) => update('type', event.target.value)}><option value="pessoa_fisica">Pessoa física</option><option value="pessoa_juridica">Pessoa jurídica</option></select></label>
    <div className="settings-grid"><Input label={data.type === 'pessoa_juridica' ? 'Razão social *' : 'Nome *'} value={data.type === 'pessoa_juridica' ? data.companyName : data.name} onChange={(value) => update(data.type === 'pessoa_juridica' ? 'companyName' : 'name', value)} /><Input label="Telefone" value={data.phone} onChange={(value) => update('phone', value)} /><Input label="E-mail" value={data.email} onChange={(value) => update('email', value)} /></div>
    <details className="optional-fields"><summary>Mais dados: documentos, endereço e relacionamento</summary><div className="settings-grid">{[['Nome de contato','contactName'],['CPF','cpf'],['CNPJ','cnpj'],['Instagram','instagram'],['Site','website'],['Cidade','city'],['Estado','state'],['Endereço','address']].map(([label,key]) => <Input key={key} label={label} value={data[key]} onChange={(value) => update(key,value)} />)}</div><label className="field"><span>Origem</span><select value={data.source} onChange={(event) => update('source',event.target.value)}>{CLIENT_SOURCES.map((source) => <option key={source}>{source}</option>)}</select></label><Input label="Tags (separadas por vírgula)" value={data.tags.join(', ')} onChange={(value) => update('tags',value.split(',').map((tag)=>tag.trim()).filter(Boolean))} /><label className="field"><span>Observações</span><textarea value={data.notes} onChange={(event)=>update('notes',event.target.value)} /></label></details></div>
    <div className="modal-actions">{error && <p role="alert">{error}</p>}<button type="button" className="button button-secondary" onClick={onClose}>Cancelar</button><button className="button" type="submit">Salvar cliente</button></div></form></div>, document.body)
}
function Input({ label, value, onChange }) { return <label className="field settings-field"><span>{label}</span><div className="input-wrap"><input required={label.includes('*')} type={label === 'E-mail' ? 'email' : 'text'} value={value || ''} onChange={(event) => onChange(event.target.value)} /></div></label> }
