import { useState } from 'react'
import { motion, useReducedMotion } from 'framer-motion'
import { calculateBudget, formatCurrency } from '../utils/calculations'

export default function LandingPage({ onEnter }) {
  const reducedMotion = useReducedMotion()
  const [hours, setHours] = useState(10)
  const [cost, setCost] = useState(100)
  const example = calculateBudget({ calculationVersion: 3, activities: [{ quantity: hours, unitValue: cost }], taxes: 6, fees: 0, profitMargin: 20 })
  return <main className="landing-page landing-v2" id="landing-top">
    <header className="landing-v2-nav"><a className="landing-brand" href="#landing-top" aria-label="Vetra, início"><span className="landing-logo">V</span>Vetra</a><button className="button button-secondary" onClick={onEnter}>Abrir workspace ↗</button></header>
    <motion.section className="landing-v2-hero" initial={reducedMotion ? false : { opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .45 }}>
      <div><span className="eyebrow">PARA FOTÓGRAFOS E VIDEOMAKERS</span><h1>Seu trabalho tem valor.<br /><em>Entenda quanto cobrar.</em></h1><p>Organize o tempo, os gastos e as entregas. Monte uma proposta com a sua tarifa ou encontre uma referência a partir dos seus custos.</p><div className="landing-v2-actions"><button className="button" onClick={onEnter}>Criar meu orçamento ↗</button><a href="#como-funciona">Como funciona ↓</a></div><small>Sem cadastro nesta versão · Dados salvos no navegador</small></div>
      <div className="landing-example"><span className="card-kicker">EXEMPLO INTERATIVO · VALORES ILUSTRATIVOS</span><h2>Veja de onde vem o preço.</h2><div className="input-grid"><label className="field"><span>Horas totais do projeto</span><input type="number" min="0" step="any" value={hours} onChange={event => setHours(event.target.value)} /></label><label className="field"><span>Custo interno por hora (R$)</span><input type="number" min="0" step="any" value={cost} onChange={event => setCost(event.target.value)} /></label></div><div className="example-result"><span>Referência de venda</span><strong>{formatCurrency(example.sustainablePrice)}</strong></div><dl><div><dt>Tempo × custo</dt><dd>{formatCurrency(example.services)}</dd></div><div><dt>Impostos incluídos (6%)</dt><dd>{formatCurrency(example.taxAmount)}</dd></div><div><dt>Resultado estimado (20%)</dt><dd>{formatCurrency(example.profitAmount)}</dd></div></dl><p>Este exemplo usa 6% de impostos, 20% de margem e nenhuma despesa extra. No seu orçamento, os dados e percentuais são definidos por você.</p></div>
    </motion.section>
    <section id="como-funciona" className="landing-v2-section"><span className="eyebrow">DO PRIMEIRO CONTATO À PROPOSTA</span><h2>Menos repetição.<br />Mais clareza em cada etapa.</h2><div className="landing-v2-grid">{[['01','Descreva o trabalho','Cliente, objetivo, agenda e entregas em um único lugar.'],['02','Conte todas as horas','Planejamento, captação, edição e entrega. Use modelos e ajuste ao seu projeto.'],['03','Entenda o preço','Compare custos, impostos, taxas e o efeito de um desconto.'],['04','Revise e apresente','Confira os dados, salve a proposta e gere um PDF para o cliente.']].map(([n,title,body]) => <article key={n}><span>{n}</span><h3>{title}</h3><p>{body}</p></article>)}</div></section>
    <section className="landing-v2-section landing-v2-workflow"><div><span className="eyebrow">UM PROJETO, UM HISTÓRICO</span><h2>Do cliente à entrega.<br />Tudo conectado.</h2><p>Reutilize os dados do cliente e mantenha proposta, minutas, autorizações e anexos juntos. Acompanhe o valor contratado e os pagamentos que você registrar.</p><p className="form-help">As minutas precisam de revisão das partes. O aplicativo não realiza assinatura eletrônica nem cobra pagamentos automaticamente.</p></div><div className="workflow-list">{['Cliente e contato','Proposta e condições','Documentos e comprovantes','Entrega e pagamentos registrados'].map((item,index) => <div key={item}><span>{index+1}</span><strong>{item}</strong></div>)}</div></section>
    <section className="landing-v2-section landing-faq"><span className="eyebrow">ANTES DE COMEÇAR</span><h2>Simples, com limites claros.</h2><details><summary>Preciso saber quanto cobrar?</summary><p>Você pode usar sua tarifa ou configurar remuneração, custos, reservas e horas faturáveis. A referência reflete os dados que você informou; não é uma cotação de mercado.</p></details><details><summary>Onde ficam meus dados?</summary><p>Neste navegador e dispositivo. Não há sincronização entre aparelhos. Exporte um backup no Perfil, especialmente antes de limpar os dados do navegador ou mudar de dispositivo.</p></details><details><summary>A Vetra já usa inteligência artificial?</summary><p>A revisão disponível usa regras locais de consistência. Nenhum dado é enviado a um provedor de IA nesta versão.</p></details><details><summary>Posso guardar um orçamento e continuar depois?</summary><p>Sim. O editor salva um rascunho local e informa o estado do salvamento. Para concluir, revise e selecione “Salvar orçamento”.</p></details></section>
    <section className="landing-v2-final"><span className="eyebrow">SEU PRÓXIMO PROJETO</span><h2>Crie com liberdade.<br /><em>Cobre com clareza.</em></h2><button className="button" onClick={onEnter}>Começar meu orçamento ↗</button></section>
    <footer className="landing-v2-footer"><strong>Vetra · VisurePictures</strong><span>Gestão e precificação para profissionais de imagem.</span><a href="#como-funciona">Como funciona</a><span>© 2026 · Dados locais, sob seu controle.</span></footer>
  </main>
}
