export function sanitizeNumber(value, fallback = 0) { const number = Number(value); return Number.isFinite(number) && number >= 0 ? number : fallback }
export function getHourlyCost(profile = {}) { const need = sanitizeNumber(profile.monthlyGoal) + sanitizeNumber(profile.monthlyCosts) + sanitizeNumber(profile.equipmentReserve) + sanitizeNumber(profile.vacationReserve); const hours = sanitizeNumber(profile.billableHours); return hours > 0 && Number.isFinite(need / hours) ? need / hours : 0 }
export function calculateDuration(startAt, endAt) { return calculateDurationParts(startAt, endAt).decimal }
export function parseLocalDateTime(value) { if (!value || typeof value !== 'string') return null; const match = value.match(/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2})$/); if (!match) return null; const [, year, month, day, hours, minutes] = match; const parts = [Number(year), Number(month), Number(day), Number(hours), Number(minutes)]; if (month < 1 || month > 12 || day < 1 || day > 31 || hours > 23 || minutes > 59) return null; const date = new Date(parts[0], parts[1] - 1, parts[2], parts[3], parts[4], 0, 0); return Number.isNaN(date.getTime()) || date.getFullYear() !== parts[0] || date.getMonth() !== parts[1] - 1 || date.getDate() !== parts[2] || date.getHours() !== parts[3] || date.getMinutes() !== parts[4] ? null : date }
export function toLocalDateTimeValue(date) { if (!(date instanceof Date) || Number.isNaN(date.getTime())) return ''; const pad = (value) => String(value).padStart(2, '0'); return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}` }
export function createDefaultDateRange() { const start = new Date(); start.setSeconds(0, 0); start.setMinutes(Math.ceil(start.getMinutes() / 5) * 5); if (start.getMinutes() === 60) { start.setHours(start.getHours() + 1, 0) } const end = new Date(start.getTime() + 3600000); return { startAt: toLocalDateTimeValue(start), endAt: toLocalDateTimeValue(end) } }
export function calculateDurationParts(startAt, endAt) { const start = parseLocalDateTime(startAt); const end = parseLocalDateTime(endAt); if (!start || !end || end <= start) return { hours: 0, minutes: 0, decimal: 0 }; const totalMinutes = Math.round((end - start) / 60000); return { hours: Math.floor(totalMinutes / 60), minutes: totalMinutes % 60, decimal: totalMinutes / 60 } }
export function isDateRangeValid(startAt, endAt, { allowPast = false } = {}) { const start = parseLocalDateTime(startAt); const end = parseLocalDateTime(endAt); if (!start || !end || end <= start) return false; if (!allowPast) { const today = new Date(); today.setHours(0, 0, 0, 0); if (start < today) return false } return true }
export function calculateBudget(budget = {}) { const activities = Array.isArray(budget.activities) ? budget.activities : []; const services = activities.reduce((sum, activity) => sum + sanitizeNumber(activity?.quantity) * sanitizeNumber(activity?.unitValue), 0); const expenses = Object.values(budget.expenses && typeof budget.expenses === 'object' ? budget.expenses : {}).reduce((sum, value) => sum + sanitizeNumber(value), 0); const directCost = services + expenses; const urgency = budget.urgent ? directCost * 0.25 : 0; const base = directCost + urgency; const taxes = Math.min(sanitizeNumber(budget.taxes) / 100, 0.99); const margin = Math.min(sanitizeNumber(budget.profitMargin) / 100, 0.99); const validSustainableDivisor = 1 - taxes - margin > 0; const minimumPrice = base > 0 && Number.isFinite(base / (1 - taxes)) ? base / (1 - taxes) : 0; const sustainablePrice = base > 0 && validSustainableDivisor && Number.isFinite(base / validSustainableDivisor) ? base / validSustainableDivisor : 0; return { services, expenses, urgency, directCost, minimumPrice, sustainablePrice, isValid: validSustainableDivisor && Number.isFinite(services) && Number.isFinite(expenses) }
}
export function formatCurrency(value) { return new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(Number.isFinite(value) ? value : 0) }
